FROM python:3.9-alpine
WORKDIR /code/getsize
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY *.py /code/getsize
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "90"]
