FROM python:3.9
WORKDIR /
COPY api.py requirements.txt /
RUN pip install --no-cache-dir --upgrade -r /requirements.txt && \
    groupadd -r user && useradd -r -g user user
USER user
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "90"]
