name: MyPipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3.8
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Testing the code with pytest
      run: |
        pytest -vv --count 1000 --durations=16
      env:
        RABBITMQ_HOST: 127.0.0.1
        RABBITMQ_ROUTING: fastapi_task
        RABBITMQ_USER: guest
        RABBITMQ_PASSWORD: guest
