name: MyPipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3.8
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672

    steps:
    - name: Run Tests
      run: |
        pip install -r requirements.txt && \
        pytest -vv --count 100 --durations=16
      env:
        RABBITMQ_HOST: 127.0.0.1
        RABBITMQ_ROUTING: fastapi_task
        RABBITMQ_USER: guest
        RABBITMQ_PASSWORD: guest
